### ISSUE TITLE
I can't open a new branch/PR

### ISSUE THREAD

**Issue by muhendiskedibey** [continuedev/prompt-file-examples#1]
Hi, I want to contribute to this library, but I can't open a new branch and therefore I can't open a pull request.

In the [following document](https://docs.continue.dev/features/prompt-files#quick-start) on your site it is written that we can open a pull request. Do I need to do it another way?

**Comment by Patrick-Erichsen** [comment]
Hi @muhendiskedibey , glad to hear you'd like to contribute! In order to open a PR you'll have to fork the repo and then open the PR.

**Comment by muhendiskedibey** [comment]
@Patrick-Erichsen Thank you, I will open a PR when ready
